swagger: "2.0"
info:
  version: "1.0.0"
  title: "API de Ejemplo"
  description: "Descripción de la API de Ejemplo."

schemes:
  - "http"
  - "https"

paths:
  /generar:
    post:
      operationId: "app.generar"
      consumes:
        - "application/x-www-form-urlencoded"
        - "multipart/form-data"
      summary: "Generar algo basado en la imagen y el prompt proporcionados"
      description: "Genera algo utilizando la imagen base64, el prompt y el neg_prompt."
      parameters:
        - name: "imgBase64"
          in: "formData"
          description: "Imagen codificada en base64"
          required: true
          type: "string"
        - name: "prompt"
          in: "formData"
          description: "Texto de estímulo para la generación"
          required: true
          type: "string"
        - name: "neg_prompt"
          in: "formData"
          description: "Texto de estímulo negativo"
          required: true
          type: "string"
      responses:
        200:
          description: "Respuesta exitosa."
          schema:
            type: "object"
            properties:
              imageBase64:
                type: "string"
                format: "byte"
